FROM openjdk:17
EXPOSE 8080
ADD github-cicd-actions/target/springbootproject-images.jar springbootproject-images.jar
ENTRYPOINT ["java","-jar","github-cicd-actions/target/springbootproject-images.jar"]